src/webapp_napilinux/forms/sensors.py
from wtforms import Form, validators, StringField, BooleanField, IntegerField, SelectField, TextAreaField
from wtforms.validators import DataRequired


class SensorsSettingsForm(Form):
    sensor = StringField("Название датчика",
                         validators=[DataRequired("Это поле необходимо заполнить"), validators.Length(max=30)])
    data_source = StringField('Источник данных (tcp, консоль)',
                              validators=[DataRequired("Это поле необходимо заполнить"), validators.Length(max=140)])
    period = IntegerField('Период опроса, мс', validators=[DataRequired(), validators.number_range(10, 3600000)],
                          default=100)
    modbus_slave_id = IntegerField('Modbus Slave ID', validators=[DataRequired(), validators.number_range(1, 247)],
                                   default=1)
    timeout = IntegerField('Таймаут опроса датчика, с', validators=[DataRequired(), validators.number_range(1, 60)],
                           default=1)
    active = BooleanField('Опрашивать датчик', default=False)


class LoraConfigForm(Form):
    appkey = StringField("AppKey",
                         validators=[DataRequired("Это поле необходимо заполнить"), validators.Length(min=32, max=32)])
    mqtttopics = StringField("mqtt topics",
                             validators=[DataRequired("Это поле необходимо заполнить"), validators.Length(max=50)])
    # loraregion = StringField("LoRa region",
    #                          validators=[DataRequired("Это поле необходимо заполнить"),
    #                                      validators.Length(min=5, max=5)])

    deviceAddress = StringField("Device address",
                                validators=[DataRequired("Это поле необходимо заполнить"), validators.Length(max=32)])
    lorafport = IntegerField('FPort', validators=[DataRequired("Это поле необходимо заполнить"),
                                                  validators.number_range(1, 233)], default=1)
    loraregion = SelectField("LoRa region", choices=[('EU868', 'EU868'), ('RU864', 'RU864'), ('IN865', 'IN865'),
                                                     ('US915', 'US915'), ('AU915', 'AU915'), ('KR920', 'KR920')])
    # submit = SubmitField("asd")


class SensorsTextConf(Form):
    conf_text_area = TextAreaField("Файл конфигурации датчика", validators=[DataRequired()])


class SensorAddConf(Form):
    sensor_name = StringField(
        "Название датчика",
        validators=[DataRequired(), validators.Length(min=2, max=20)]
    )
    conf_text = TextAreaField(
        "Конфигурация",
        validators=[DataRequired()]
    )

src/webapp_napilinux/sensors/__init__.py
from flask import Blueprint
from .routes import routes

bp = Blueprint('sensors', __name__)

routes(bp)

src/webapp_napilinux/sensors/routes.py
import glob
import shutil
from os import path, remove, mkdir

from flask_login import login_required
from werkzeug.security import safe_join
from werkzeug.utils import secure_filename

from ..forms.sensors import SensorsTextConf, SensorAddConf

from flask import render_template, current_app, flash, request, redirect, url_for, send_file

from ..utils import allowed_file, sys_service_manage


def routes(bp):
    @bp.route("/", methods=['GET'])
    @login_required
    def index():
        def read_comment():
            comment = str()
            with open(upload_path, "r") as file:
                lines = file.readlines()
                for line in lines:
                    if line.startswith('##'):
                        comment = line.split('##', 1)[1]
                file.close()
            return comment

        sensors_list = list()
        for f in reversed(sorted(glob.glob(current_app.config["UPLOAD_FOLDER"] + "*.conf"), key=path.getmtime)):
            name = str(f).split("/")[-1].split(".")[0]
            active_path = safe_join(current_app.config["ACTIVE_FOLDER"], f"{name}.conf")
            upload_path = safe_join(current_app.config["UPLOAD_FOLDER"], f"{name}.conf")
            active = path.exists(active_path)
            comment_line = read_comment()
            sensors_list.append((name, comment_line, active,))
        return render_template('sensors/index.html', sensors_list=sensors_list)


    @bp.route('/upload', methods=['GET'])
    @login_required
    def upload_sensor():      
        return render_template('sensors/upload.html'), 201

    @bp.route('/add', methods=['GET'])
    @login_required
    def add_sensor():
        form = SensorAddConf()
        return render_template('sensors/add.html', form=form)

    @bp.route("/<sensor_name>", methods=['GET', 'POST'])
    @login_required
    def sensor(sensor_name):
        # form = SensorsSettingsForm(request.form)
        filename = f'{sensor_name}.conf'
        active_path = safe_join(current_app.config["ACTIVE_FOLDER"], filename)
        upload_path = safe_join(current_app.config["UPLOAD_FOLDER"], filename)
        active_folder_path = safe_join(current_app.config["ACTIVE_FOLDER"])

        # View *.conf URL param
        view_conf = request.args.get('view')

        if request.method == 'GET' and view_conf == 'y':
            with open(upload_path, "r") as f:
                text = f.read()
                f.close()
            return render_template('sensors/viewconf.html', text=text)

        # Download *.conf URL param
        download_conf = request.args.get('download')

        if request.method == 'GET' and download_conf == 'y':
            return send_file(upload_path, as_attachment=True)

        # Delete *.conf URL param
        delete_conf = request.args.get('delete')

        if request.method == 'GET' and delete_conf == 'y':
            if path.exists(active_path) is True:
                flash('Шаблон активен, удалить невозможно!')
            else:
                try:
                    remove(upload_path)
                except FileNotFoundError:
                    return 'Ошибка удаления файла, файл конфигурации не найден', 404
            return redirect(request.referrer)

        # Enabled  *.conf URL param
        enable_conf = request.args.get('enable')

        if request.method == 'GET' and enable_conf == 'y':
            if path.exists(upload_path) is True:
                # Create dir if not exist
                if path.exists(active_folder_path) is False:
                    mkdir(active_folder_path)
                if path.exists(active_path) is False:
                    shutil.copyfile(upload_path, active_path)
                    sys_service_manage('telegraf')
                else:
                    flash("Шаблон уже активен!")
                return redirect(url_for('sensors.index', name=filename))

        # Disabled *.conf URL param
        disable_conf = request.args.get('disable')

        if request.method == 'GET' and disable_conf == 'y':
            if path.exists(active_path):
                remove(active_path)
                sys_service_manage('telegraf')
            else:
                flash('Шаблон по какой-то причине отсутствует в списке активных')
            return redirect(url_for('sensors.index', name=filename))

        # Upgrade *.conf URL param
        form_conf = SensorsTextConf()

        upg_conf = request.args.get('upg')

        if request.method == 'POST' and upg_conf == 'y':
            conf_text = request.form.get(form_conf.conf_text_area.name)
            with open(active_path, 'w') as f_new:
                f_new.write(str(conf_text))
                f_new.close()
            sys_service_manage('telegraf')
            return redirect(request.referrer)

        def readfile():
            with open(active_path, "r") as fa:
                read_file = fa.read()
                # text = text.replace('\n', '<br>')
                # return Response(text, mimetype='application/toml')
                fa.close()
                return read_file

        if path.exists(active_path) is True:
            text = readfile()
        else:
            flash("Сперва нужно активировать шаблон.")

            return redirect(url_for('sensors.index', name=filename))
        return render_template('sensors/sensor.html', text=text, form_conf=form_conf, current_sensor=request.path)

src/webapp_napilinux/templates/sensors/add.html
{% extends "base.html" %}
{% block title %}Настройка конфигурации{% endblock %}
{% block title_page %}Настройка датчика{% endblock %}
{% block content %}

<div class="alert alert-secondary alert-dismissible fade show text-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
  Более полную информацию по написанию файла конфигурации вы можете найти на
    <a href="https://github.com/influxdata/telegraf/tree/master/plugins/inputs/modbus#configuration"
                                                                                 class="alert-link"
                                                                                 target="_blank">Github</a>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<form class="was-validated g-3" method="POST" action="{{ url_for('sensors.add_sensor') }}">
    <br>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" id="{{ form.sensor_name.name }}" name="{{ form.sensor_name.name }}"
               placeholder="Sensor-1-1" maxlength="20" minlength="2" required>
        <label for="{{ form.sensor_name.name }}">{{ form.sensor_name.label }}</label>
    </div>
    <pre>
        <textarea class="form-control text-field" id="{{ form.conf_text.name }}"
                  name="{{ form.conf_text.name }}"
                  rows="25">## Тут пишем комментарий
[[inputs.modbus]]

  name = "SensorName"
  slave_id = 1
  timeout = "1s"

  controller = "file:///dev/ttyS1"
  baud_rate = 9600
  data_bits = 8
  parity = "N"
  stop_bits = 1
  transmission_mode = "RTU"

  holding_registers = [
    { name = "Volt_a",   byte_order = "AB",   data_type = "UINT16",   scale=0.01,     address = [72]},
  ]
</textarea>
    </pre>
    <button class="btn btn-primary confirm-button" type="button" value="Добавить">
        Добавить
    </button>
    <br>
</form>

<script src="{{ url_for('static', filename='bootstrap/js/select_options_button_handler.js') }}"></script>

<script>
let confirmButton = document.querySelector('.confirm-button');
let textField = document.querySelector('text-field');
data = textField.innerHTML;
console.log(data);
returnData = await postJSON("/api/sensors/create", "POST", data);


</script>


<script src="{{ url_for('static', filename='codemirror/lib/codemirror.js') }}"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='codemirror/lib/codemirror.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='codemirror/theme/dracula.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='codemirror/addon/hint/show-hint.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='codemirror/addon/display/fullscreen.css') }}">
<script src="{{ url_for('static', filename='codemirror/mode/toml/toml.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/selection/active-line.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/search/searchcursor.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/search/match-highlighter.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/hint/show-hint.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/hint/anyword-hint.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/edit/closebrackets.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/edit/trailingspace.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/display/fullscreen.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/edit/matchbrackets.js') }}"></script>
<style type="text/css">
.CodeMirror {
    height: auto;
}
.CodeMirror-focused .cm-matchhighlight {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAFklEQVQI12NgYGBgkKzc8x9CMDAwAAAmhwSbidEoSQAAAABJRU5ErkJggg==);
        background-position: bottom;
        background-repeat: repeat-x;
      }
      .cm-matchhighlight {background-color: rgba(0, 255, 0, 0.2)}
.cm-trailingspace {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAACCAYAAAB/qH1jAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QUXCToH00Y1UgAAACFJREFUCNdjPMDBUc/AwNDAAAFMTAwMDA0OP34wQgX/AQBYgwYEx4f9lQAAAABJRU5ErkJggg==);
    background-position: bottom left;
    background-repeat: repeat-x;
}
.CodeMirror-fullscreen {
    top: 5em;
}
.cm-s-dracula .CodeMirror-matchingbracket { text-decoration: none; color: #f5f502 !important; }
</style>

<script type="text/javascript">
CodeMirror.commands.autocomplete = function(cm) {
        cm.showHint({hint: CodeMirror.hint.anyword});
      }
var editor = CodeMirror.fromTextArea(
    document.getElementById('{{ form.conf_text.name }}'), {
        mode:'toml',
        theme: 'dracula',
        lineNumbers: true,
        styleActiveLine: true,
        lineWrapping: true,
        highlightSelectionMatches: {showToken: /\w/},
        extraKeys: {
          "Ctrl-Space": "autocomplete",
          "F11": function(cm) {
          cm.setOption("fullScreen", !cm.getOption("fullScreen"));
          },
          "Esc": function(cm) {
            if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
          }
        },
        autoCloseBrackets: true,
        showTrailingSpace: true,
        matchBrackets: true,
        showCursorWhenSelecting: true
        });
</script>
{% endblock %}

src/webapp_napilinux/templates/sensors/index.html
{% extends "base.html" %}
{% block title %}Шаблоны конфигураций{% endblock %}
{% block title_page %}Панель управления конфигурациями{% endblock %}
{% block content %}
    <div class="mb-3">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
                <br>
              <div class="alert alert-danger shadow-sm p-3 mb-5 rounded" role="alert">
                  {{ message }}
              </div>
            {% endfor %}
    </div>
          {% else %}
    <div class="clearfix py-2">
        <p class="lead float-start">Загруженные шаблоны конфигурации:</p>
        <div class="float-end d-grid gap-2 d-md-block">
            <a href="{{ url_for('sensors.add_sensor') }}">
            <button type="button" class="btn btn-success">
                <svg class="bi me-2 theme-icon"><use href="#code_icon"></use></svg>Написать шаблон
            </button>
            </a>
            <a href="{{ url_for('sensors.upload_sensor') }}">
            <button type="button" class="btn btn-success">
                <svg class="bi me-2 theme-icon"><use href="#plus"></use></svg>Загрузить шаблон
            </button>
            </a>
        </div>
    </div>
    <ol class="list-group list-group-numbered">
    {% for sensor in sensors_list %}
      <li class="list-group-item">
          {{ sensor[0] }}
          {% if sensor[1] %}
          <text class="text-secondary-emphasis">: {{ sensor[1] }}</text>
          {% endif %}
          <div class="d-grid gap-2 d-md-flex justify-content-md-end text-end">
              {% if sensor[2] == True %}
              <a href="{{ url_for('sensors.sensor', sensor_name=sensor[0]) }}">
                  <button type="submit" class="btn btn-warning btn-sm">
                      <svg class="bi me-1 opacity-75 theme-icon"><use href="#bi-pencil-square"></use></svg>
                      Редактировать
                  </button>
              </a>
              <a href="{{ url_for('sensors.sensor', sensor_name=sensor[0], view='y') }}">
                  <button type="submit" class="btn btn-primary btn-sm">
                      <svg class="bi me-1 opacity-75 theme-icon"><use href="#bi-eye"></use></svg>
                      Оригинал
                  </button>
              </a>
              <a href="{{ url_for('sensors.sensor', sensor_name=sensor[0], download='y') }}">
                  <button type="submit" class="btn btn-secondary btn-sm">
                      <svg class="bi me-1 opacity-75 theme-icon"><use href="#download"></use></svg>
                      Скачать
                  </button>
              </a>
              <a href="{{ url_for('sensors.sensor', sensor_name=sensor[0], disable='y') }}">
                  <button type="submit" class="btn btn-danger btn-sm">
                      <svg class="bi me-1 opacity-75 theme-icon"><use href="#bi-stop-circle-fill"></use></svg>
                      Отключить
                  </button>
              </a>
              {% else %}
              <a href="{{ url_for('sensors.sensor', sensor_name=sensor[0], enable='y') }}">
                  <button type="submit" class="btn btn-success btn-sm">
                      <svg class="bi me-1 opacity-75 theme-icon"><use href="#bi-play-circle-fill"></use></svg>
                      Включить
                  </button>
              </a>
              <a href="{{ url_for('sensors.sensor', sensor_name=sensor[0], view='y') }}">
                  <button type="submit" class="btn btn-primary btn-sm">
                      <svg class="bi me-1 opacity-75 theme-icon"><use href="#bi-eye"></use></svg>
                      Оригинал
                  </button>
              </a>
              <a href="{{ url_for('sensors.sensor', sensor_name=sensor[0], download='y') }}">
                  <button type="submit" class="btn btn-secondary btn-sm">
                      <svg class="bi me-1 opacity-75 theme-icon"><use href="#download"></use></svg>
                      Скачать
                  </button>
              </a>
              <a href="{{ url_for('sensors.sensor', sensor_name=sensor[0], delete='y') }}">
                  <button type="submit" class="btn btn-danger btn-sm">
                      <svg class="bi me-1 opacity-75 theme-icon"><use href="#bi-trash3-fill"></use></svg>
                      Удалить
                  </button>
              </a>
              {% endif %}
              </div>
      </li>
    {% endfor %}
            </div>
    </ol>
          {% endif %}
        {% endwith %}
{% endblock %}

src/webapp_napilinux/templates/sensors/sensor.html
{% extends "base.html" %}
{% block title %}Настройка конфигурации{% endblock %}
{% block title_page %}Настройка датчика{% endblock %}
{% block content %}


<form class="g-3" method="POST" action="{{ current_sensor + '?upg=y' }}">
    <button class="btn btn-primary" type="submit" value="Применить">
        Применить
    </button>
    <br><pre>
        <textarea class="form-control" id="{{ form_conf.conf_text_area.name }}"
                  name="{{ form_conf.conf_text_area.name }}"
                  rows="25">{{ text }}</textarea>
    </pre>
</form>

<script src="{{ url_for('static', filename='codemirror/lib/codemirror.js') }}"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='codemirror/lib/codemirror.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='codemirror/theme/dracula.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='codemirror/addon/hint/show-hint.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='codemirror/addon/display/fullscreen.css') }}">
<script src="{{ url_for('static', filename='codemirror/mode/toml/toml.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/selection/active-line.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/search/searchcursor.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/search/match-highlighter.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/hint/show-hint.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/hint/anyword-hint.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/edit/closebrackets.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/edit/trailingspace.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/display/fullscreen.js') }}"></script>
<script src="{{ url_for('static', filename='codemirror/addon/edit/matchbrackets.js') }}"></script>
<style type="text/css">
.CodeMirror {
    height: auto;
}
.CodeMirror-focused .cm-matchhighlight {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAFklEQVQI12NgYGBgkKzc8x9CMDAwAAAmhwSbidEoSQAAAABJRU5ErkJggg==);
        background-position: bottom;
        background-repeat: repeat-x;
      }
      .cm-matchhighlight {background-color: rgba(0, 255, 0, 0.2)}
.cm-trailingspace {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAACCAYAAAB/qH1jAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QUXCToH00Y1UgAAACFJREFUCNdjPMDBUc/AwNDAAAFMTAwMDA0OP34wQgX/AQBYgwYEx4f9lQAAAABJRU5ErkJggg==);
    background-position: bottom left;
    background-repeat: repeat-x;
}
.CodeMirror-fullscreen {
    top: 5em;
}
.cm-s-dracula .CodeMirror-matchingbracket { text-decoration: none; color: #f5f502 !important; }
</style>

<script type="text/javascript">
CodeMirror.commands.autocomplete = function(cm) {
        cm.showHint({hint: CodeMirror.hint.anyword});
      }
var editor = CodeMirror.fromTextArea(
    document.getElementById('{{ form_conf.conf_text_area.name }}'), {
        mode:'toml',
        theme: 'dracula',
        lineNumbers: true,
        styleActiveLine: true,
        lineWrapping: true,
        highlightSelectionMatches: {showToken: /\w/},
        extraKeys: {
          "Ctrl-Space": "autocomplete",
          "F11": function(cm) {
          cm.setOption("fullScreen", !cm.getOption("fullScreen"));
          },
          "Esc": function(cm) {
            if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
          }
        },
        autoCloseBrackets: true,
        showTrailingSpace: true,
        matchBrackets: true,
        showCursorWhenSelecting: true
        });
</script>

{% endblock %}

src/webapp_napilinux/templates/sensors/upload.html
{% extends "base.html" %}
{% block title %}Шаблоны конфигураций{% endblock %}
{% block title_page %}Загрузка конфигурации датчика{% endblock %}
{% block content %}
    <p class="fw-lighter">Максимальный размер файла 15KB (*.conf)</p>
    <div class="mb-3">
        <form action = "{{ url_for('sensors.upload_sensor') }}" method = "POST" enctype = "multipart/form-data">
          <input class="form-control" type="file" name = "file" accept=".conf" id="formFile" />
            <br>
            <button type="submit" class="btn btn-primary">
                <svg class="bi me-1 opacity-75 theme-icon"><use href="#bi-upload"></use></svg>
                Загрузить
            </button>
        </form>
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
            <br>
              <div class="alert alert-danger shadow-sm p-3 mb-5 rounded" role="alert">
                  {{ message }}
              </div>
            {% endfor %}

          {% else %}
          {% endif %}
        {% endwith %}
    </div>
{% endblock %}

src/webapp_napilinux/templates/sensors/viewconf.html
{% extends "base.html" %}
{% block title %}Просмотр конфигурации{% endblock %}
{% block title_page %}Просмотр конфигурации{% endblock %}
{% block content %}
<div class="alert alert-secondary alert-dismissible fade show text-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
    Чтобы отредактировать этот шаблон, сперва нужно его активировать, либо загрузите шаблон в нужной конфигурации!
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<a href="{{ url_for('sensors.index') }}"><button type="submit" class="btn btn-primary">Назад</button></a>
<hr>
<pre>
    <code class="language-toml">
        {{ text }}
    </code>
</pre>
<hr>
<a href="{{ url_for('sensors.index') }}"><button type="submit" class="btn btn-primary">Назад</button></a>
<hr>

<link rel="stylesheet" href="/static/css/github.min.css">
<script src="/static/js/highlight.min.js"></script>
<script>hljs.highlightAll();</script>
{% endblock %}