src/webapp_napilinux/forms/network.py
from wtforms import Form, BooleanField, StringField
from wtforms.validators import InputRequired, DataRequired, IPAddress


class NetworkForm(Form):
    dhcp = BooleanField('DHCP', validators=[DataRequired(), ])
    ip = StringField('IP', validators=[InputRequired(), IPAddress(message='Укажите ip!')])
    gw = StringField('Шлюз', validators=[InputRequired(), IPAddress(message='Укажите шлюз!')])
    dns = StringField('DNS', validators=[InputRequired(), IPAddress(message='Укажите DNS!')])

src/webapp_napilinux/settings/__init__.py
from flask import Blueprint
from .routes import routes

bp = Blueprint('settings', __name__)


routes(bp)

src/webapp_napilinux/settings/routes.py
import os.path
import subprocess

from os import path, popen

from flask_login import login_required
from werkzeug.security import safe_join

from ..forms.network import NetworkForm
from ..forms.sensors import LoraConfigForm

from flask import render_template, flash, current_app, request, redirect, url_for, jsonify
from ..utils import (sys_uptime, sys_date, sys_ram, sys_cpu_avg, sys_disk, sys_wired_network_config, SysConfig,
                       sys_service_manage, db_size, ModemControl, findparam)


def routes(bp):
    @bp.route("/")
    @login_required
    def index():
        uptime = str(sys_uptime())
        ram = str(sys_ram())
        cpu_avg = str(sys_cpu_avg())
        disk = str(sys_disk())
        db = str(db_size())

        return render_template(
            'settings/index.html',
            uptime=uptime,
            ram=ram,
            cpu_avg=cpu_avg,
            disk=disk,
            db=db,
        ) 
    
    @bp.route('/lora', methods=['GET', 'POST'])
    @login_required
    def lora_settings():

        def replaceparam(_path, key_to_replace, word):
            with open(_path, "r+") as lora_cfg:
                # Read the file line by line
                lines = lora_cfg.readlines()

                # Loop through the lines and find the key to replace
                for i, line in enumerate(lines):
                    if line.startswith(key_to_replace + "="):
                        # If the key is found, replace its value
                        lines[i] = key_to_replace + "=" + word + "\n"
                        break

                # Write the modified lines back to the file
                lora_cfg.seek(0)
                lora_cfg.writelines(lines)
                lora_cfg.close()

        form = LoraConfigForm()
        file = safe_join(current_app.config["LORABRIDGE_CFG"])
        loraappkey = findparam(file, 'appkey')
        mqtttopic = findparam(file, 'mqttTopics')
        lorafport = findparam(file, 'fport')
        deviceAddress = findparam(file, 'deviceAddress')
        loraregions = findparam(file, 'region').split()[0]
        choise_region = form.loraregion.choices
        sw_reset = request.args.get('sw-reset')
        if request.method == 'POST':
            loraappkeynew = request.form.get(form.appkey.name)
            replaceparam(file, 'appkey', loraappkeynew)
            mqtttopicnew = request.form.get(form.mqtttopics.name)
            replaceparam(file, 'mqttTopics', mqtttopicnew)
            loraregionnew = request.form.get(form.loraregion.name)
            replaceparam(file, 'region', loraregionnew)
            lora_fport_new = request.form.get(form.lorafport.name)
            replaceparam(file, 'fport', lora_fport_new)
            deviceAddress_new = request.form.get(form.deviceAddress.name)
            replaceparam(file, 'deviceAddress', deviceAddress_new)
            # flash('Сохранено!')
            return redirect(request.referrer)
        if request.method == 'GET' and sw_reset == 'y':
            lbr_stop = [f"sudo systemctl stop lorabridge.service"]
            lbr_start = [f"sudo systemctl start lorabridge.service"]
            try:
                subprocess.check_output(lbr_stop, universal_newlines=True, shell=True)
                popen("/usr/bin/lorabridge --help").read()
                subprocess.check_output(lbr_start, universal_newlines=True, shell=True)
            except subprocess.CalledProcessError:
                flash("Недостаточно системных прав!")
                pass
            return redirect(request.referrer)

        return render_template(
            'settings/lora.html',
            form=form,
            loraappkey=loraappkey,
            loraregions=loraregions,
            mqtttopic=mqtttopic,
            choise_region=choise_region,
            sw_reset=sw_reset,
            lorafport=lorafport,
            deviceAddress=deviceAddress
        )

    @bp.route("/network", methods=['GET', 'POST'])
    @login_required
    def network_settings():
        nw_form = NetworkForm()
        # TODO: получать статус из файла конфигурации?
        network = SysConfig()
        dhcp_status = network.net_config_read('DHCP')
        ip_status = network.net_config_read('Address')
        gw_status = network.net_config_read('Gateway')
        dns_status = network.net_config_read('DNS')

        if request.method == 'POST':
            config_input = (request.form.get(nw_form.dhcp.name),
                            request.form.get(nw_form.ip.name),
                            request.form.get(nw_form.gw.name),
                            request.form.get(nw_form.dns.name)
                            )
            # DHCP, Ip, Gateway, DNS
            sys_wired_network_config(config_input)
            sys_service_manage('systemd-networkd')
            return redirect(url_for('settings.network_settings'))
        return render_template(
            'settings/network.html',
            nw_form=nw_form,
            dhcp_status=dhcp_status,
            ip=ip_status,
            gw=gw_status,
            dns=dns_status,
            ip_current=network.ip_current()
        )

    @bp.route("/firmware", methods=['GET', 'POST'])
    @login_required
    def firmware_settings():
        return render_template(
            'settings/firmware.html'
        )

    @bp.route("/modem")
    @login_required
    def modem_settings():
        """Основная функция, связанная с URL адресом /settings/modem."""
        modem = ModemControl()
        show_modem = modem.getter()
        output_form = {
            'show_modem': show_modem     
        }
        return render_template("/settings/modem.html",
                               form=output_form)

    @bp.route("/overlays", methods=['GET', 'POST'])
    @login_required
    def modem_overlays_control():
        feedback_value = str()
        file_path = "/boot/uEnv.txt"
        overlays_path = "/boot/overlays"
        mutual_exclusive_overlays = (('UART0', 'SPI0'), ('UART1', 'I2C0', 'SPI2'), ('SPI2', 'UART2'),
                                     ('GPIO3', 'SPI1', 'UART3'), ('GPIO4', 'UART4'))
        current_overlays = list()
        overlays_uart_groups = {"Interface_" + str(key): list() for key in range(len(mutual_exclusive_overlays))}
        overlays_ungrouped = list()
        unfiltered_overlays_list = list()
        switch_group_ungroup = False
        rk3308_overlays = list()
        dir_value = os.listdir(overlays_path)
        for file in dir_value:
            filename, ext = os.path.splitext(file)
            unfiltered_overlays_list.append(filename)
            if 'rk3308' in filename.lower():
                rk3308_overlays.append(filename)
                for group_index, group_tuple in enumerate(mutual_exclusive_overlays):
                    for exclusive in group_tuple:
                        if exclusive.lower() in filename.lower():
                            overlays_uart_groups["Interface_" + str(group_index)].append(filename)
                            switch_group_ungroup = True
                if not switch_group_ungroup:
                    overlays_ungrouped.append(filename)
                switch_group_ungroup = False

        if request.method == 'POST':
            row_index = int()
            switch = False
            with (open(file_path, 'r') as uboot_config):
                lines = uboot_config.readlines()
                for line in lines:
                    if 'overlays=' in line:
                        cut = line[len('overlays='):]
                        break
                current_overlays_change = cut.split(' ')
                current_overlays_change[-1] = current_overlays_change[-1][:-1]
                print(current_overlays_change)

                for key, value in overlays_uart_groups.items():
                    check = request.form.get(key)
                    if check is not None:

                        for check_element in value:
                            for change_index, test_element in enumerate(current_overlays_change):
                                if check_element == test_element:
                                    current_overlays_change[change_index] = check
                                    switch = True
                                    break
                        if not switch:
                            current_overlays_change.insert(0, check)
                        elif switch:
                            switch = False
                    else:
                        for check_element in value:
                            for change_index, test_element in enumerate(current_overlays_change):
                                if check_element == test_element:
                                    current_overlays_change.pop(change_index)

                switch = False
                for item in overlays_ungrouped:
                    check = request.form.get(item)

                    if check is not None:
                        print(check)
                        for change_index, test_element in enumerate(current_overlays_change):
                            if check == test_element:
                                switch = True
                                break
                        if not switch:
                            current_overlays_change.insert(0, check)
                        elif switch:
                            switch = False
                    else:
                        for change_index, test_element in enumerate(current_overlays_change):
                            if item == test_element:
                                print('change')
                                print(change_index)
                                current_overlays_change.pop(change_index)
                for index_temp, line in enumerate(lines):
                    if 'overlays=' in line:
                        row_index = index_temp
                        break

src/webapp_napilinux/templates/settings/firmware.html
{% extends "base.html" %}
{% block title %}Обновление прошивки{% endblock %}
{% block title_page %}Обновление прошивки{% endblock %}
{% block content %}

<div class="row md-6 d-flex justify-content-center">
    <div class="col-md-6">
    <div class="card">
        <div class="card-header">
            Текущие версии
        </div>
        <table class="table table-striped table-borderless text-center" style="margin: auto;">
            <tr>
              <th scope="row">Аппаратная версия:</th>
              <td>{{ config.HW_VERSION }}</td>
            </tr>
            <tr>
              <th scope="row">Версия ПО:</th>
              <td>{{ config.SW_VERSION }}</td>
            </tr>
            <tr>
              <th scope="row">Версия web:</th>
              <td>{{ config.WEB_VERSION }}</td>
            </tr>
        </table>
<!--        <ul class="list-group list-group-flush">-->
<!--            <li class="list-group-item white-space">test</li>-->
<!--        </ul>-->
    </div>
        </div>
</div>
<br>
<div class="row d-flex justify-content-center">
    <div class="col-md-6">
        <div class="card text-center">
            <div class="card-header">
               Обновление прошивки
            </div>
            <div class="card-body">
                <form class="g-3 input-form"  enctype="multipart/form-data">
                    <input class="form-control" type="file" accept=".swu" />
                    <br>
                    <button class="btn btn-primary" type="button" value="Применить">
                        Обновить
                    </button>
                </form>
            </div>
        </div>
        <br>
    </div>
</div>

<div class="row d-flex justify-content-center">
    <div class="col-md-6">
        <div class="card text-center">
            <div class="card-header">
               Лог
            </div>
            <div class="card-body">
                <div class="log-output">

                </div>
            </div>
        </div>
        <br>
    </div>
</div>
{% endblock %}

{% block scripts %}

<script>
let log_output = document.querySelector('.log-output');
let input_form = document.querySelector('.input-form');
let input_button = input_form.querySelector('button');

log_output.innerHTML = 'Welcome to the log output!' + '<br>';
input_button.addEventListener('click', async () =>
{
    log_output.innerHTML += 'Begin file transfer' + '<br>';

    let file = input_form.querySelector('input[type="file"]').files[0];
    let formData = new FormData();
    formData.append('file', file);
    // log_output.innerHTML +=  `<p class="progress-bar"></p> <br>`;
    let response = await fetch("/api/settings/update", {
      method: "PUT",
      body: formData,
    });
    let result = await response.json();
    log_output.innerHTML += result['message'] + "<br>";

    let eventSource = new EventSource(`/api/settings/sse?target=update`);
    eventSource.onmessage = function(event)
    {
        log_output.innerHTML += event.data + "<br>";
    }
    eventSource.onerror = (event) => {
        eventSource.close();
        log_output.innerHTML += "Connection closed" + "<br>";
    };
})
</script>
{% endblock %}

src/webapp_napilinux/templates/settings/lora.html
{% extends "base.html" %}
{% block title %}Настройка LoRa{% endblock %}
{% block title_page %}Настройка LoRa модема{% endblock %}
{% block content %}
<div class="mb-3">
    <p class="fs-5">Статус модема <span class="badge bg-success">connected</span></p>
</div>
<form class="was-validated" method="POST">
    {{ form.csrf_token }}
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-{{ form.appkey.name }}">{{ form.appkey.label }}</span>
        <input placeholder="Пример: A7CDD6A3E44ECE268005952F9536BA7A" value="{{ loraappkey }}"
               type="text" maxlength="32" minlength="32"
               class="form-control" id="{{ form.appkey.name }}" name="{{ form.appkey.name }}"
               required>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-{{ form.deviceAddress.name }}">{{ form.deviceAddress.label }}</span>
        <input placeholder="Пример: 017c3146" value="{{ deviceAddress }}"
               type="text" maxlength="32" minlength="6"
               class="form-control" id="{{ form.deviceAddress.name }}" name="{{ form.deviceAddress.name }}"
               required>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-{{ form.lorafport.name }}">{{ form.lorafport.label }}</span>
        <input placeholder="Диапазон от 1 до 233" value="{{ lorafport }}"
               type="text" maxlength="3" minlength="1"
               class="form-control" id="{{ form.lorafport.name }}" name="{{ form.lorafport.name }}"
               required>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-{{ form.loraregion.name }}">{{ form.loraregion.label }}</span>
        <select class="form-select" id="{{ form.loraregion.name }}" name="{{ form.loraregion.name }}" aria-label="{{ form.loraregion.name }}">
            {% for label, val in choise_region %}
                {% if val == loraregions %}
                    <option value="{{ val }}" selected>{{ label }}</option>
                {% else %}
                    <option value="{{ val }}">{{ label }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon2">{{ form.mqtttopics.label }}</span>
        <input placeholder="Пример: /sensor1/#/temp" value="{{ mqtttopic }}"
               type="text" minlength="1"
               class="form-control" id="{{ form.mqtttopics.name }}" name="{{ form.mqtttopics.name }}"
               required>
    </div>
    <div class="clearfix">
        <button type="submit" class="btn btn-primary float-start">Сохранить</button>
        <a class="float-end" href="{{ '/settings/lora?sw-reset=y' }}">
          <button type="submit" class="btn btn-danger">
              Программный сброс модема
          </button>
        </a>
    </div>
    {% if form.errors %}
        <ul class="errors">
        {% for error in form.errors %}
            <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}
</form>
<br>
{% endblock %}

src/webapp_napilinux/templates/settings/network.html
{% extends "base.html" %}
{% block title %}Настройка сети{% endblock %}
{% block title_page %}Настройка сети{% endblock %}
{% block content %}

<div class="row d-flex justify-content-center">
    <div class="col-md-6">
        <div class="card text-center">
            <div class="card-header">
               Сеть
            </div>
            <div class="card-body">
                <form class="g-3" method="post" action="{{ url_for('settings.network_settings') }}">
                    <div class="form-check form-switch text-start">
                        <label class="form-check-label" for="{{ nw_form.dhcp.name }}">{{ nw_form.dhcp.label }}</label>
                        <input class="form-check-input" type="checkbox" role="switch" id="{{ nw_form.dhcp.name }}"
                        name="{{ nw_form.dhcp.name }}" {% if dhcp_status %} checked {% endif %}>
                    </div>
                    <br>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-{{ nw_form.ip.name }}">{{ nw_form.ip.label }}</span>
                        <input placeholder="Пример: 192.168.1.10/24" value="{{ ip }}"
                               class="form-control" id="{{ nw_form.ip.name }}" name="{{ nw_form.ip.name }}"
                               required {% if dhcp_status %} disabled readonly {% endif %}>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-{{ nw_form.gw.name }}">{{ nw_form.gw.label }}</span>
                        <input placeholder="Пример: 192.168.1.1" value="{{ gw }}"
                               class="form-control" id="{{ nw_form.gw.name }}" name="{{ nw_form.gw.name }}"
                               required {% if dhcp_status %} disabled readonly {% endif %}>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-{{ nw_form.dns.name }}">{{ nw_form.dns.label }}</span>
                        <input placeholder="Пример: 1.1.1.1" value="{{ dns }}"
                               class="form-control" id="{{ nw_form.dns.name }}" name="{{ nw_form.dns.name }}"
                               required {% if dhcp_status %} disabled readonly {% endif %}>
                    </div>
                    <button class="btn btn-primary" type="submit" value="Применить">
<!--                        <svg class="bi me-1 opacity-75 theme-icon"><use href="#bi-box-arrow-in-right"></use></svg>-->
                        Применить
                    </button>
                </form>
            </div>
        </div>
        <br>
            <div class="card">
              <div class="card-header">
                Текущие сетевые настройки
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item white-space">{{ ip_current }}</li>
              </ul>
            </div>
        <div class="mb-3">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
                <br>
              <div class="alert alert-danger shadow-sm p-3 mb-5 rounded" role="alert">
                  {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        </div>
    </div>
</div>
<script>
    const disableInputsCheckbox = document.getElementById("{{ nw_form.dhcp.name }}");
    const input1 = document.getElementById('{{ nw_form.ip.name }}');
    const input2 = document.getElementById('{{ nw_form.gw.name }}');
    const input3 = document.getElementById('{{ nw_form.dns.name }}');

    disableInputsCheckbox.addEventListener("change", () => {
      if (disableInputsCheckbox.checked) {
        input1.disabled = true;
        input2.disabled = true;
        input3.disabled = true;
        input1.setAttribute("readonly", true);
        input2.setAttribute("readonly", true);
        input3.setAttribute("readonly", true);
      } else {
        input1.disabled = false;
        input2.disabled = false;
        input3.disabled = false;
        input1.removeAttribute("readonly");
        input2.removeAttribute("readonly");
        input3.removeAttribute("readonly");
      }
    });
</script>
{% endblock %}

src/webapp_napilinux/templates/settings/overlays.html
{% extends "base.html" %}
{% block title %}Выбор оверлеев{% endblock %}
{% block title_page %}Список доступных оверлеев{% endblock %}
{% block content %}

<div class="row justify-content-center">
    <div class="col md-6">
        <div class="card">

        <div class="card-header">
            Список интерфейсов
        </div>
        <form  method="post" action="{{ url_for('settings.modem_overlays_control') }}">

        <div class="card-body">

                {% for key, list in overlays_list.items() %}
                {% if list %}

                <div class="group-container-custom">
                    <div>{{ key | safe }}</div>

                    <div class="mt-2 btn-group interface-group" role="group" aria-label="Mutual Exclusive overlays">

                        {% for overlay in list %}
                                <input type="radio" class="btn-check" name="{{ key | safe }}"
                                       id="{{ overlay | safe }}" value="{{ overlay | safe }}" autocomplete="off"
                                        {% for current in current_overlays %}
                                            {% if overlay == current %}
                                                checked
                                            {% endif %}
                                        {% endfor %}>
                                <label class="btn btn-outline-primary" for="{{ overlay | safe }}">
                                    {{ overlay | safe }}</label>
                        {% endfor %}

                        <input type="button" class="btn btn-outline-info clear-btn" value="Сбросить выбор">
                    </div>
                </div>
                {% endif %}

            {% endfor %}


            <div class="card-header mt-3"> Доступные оверлеи </div>


            {% for item in overlays_ungrouped %}
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="{{ item | safe }}" value="{{ item | safe }}"
                           name="{{ item | safe }}"
                        {% for current in current_overlays %}
                            {% if item == current %}
                                checked
                            {% endif %}
                        {% endfor %}>
                  <label class="form-check-label" for="{{ item | safe }}">{{ item | safe }}</label>
                </div>
            {% endfor %}

        </div>

        <div class="card-footer">
            <button class="btn btn-primary" type="submit">
                Отправить
            </button>
        </div>

        </form>

        </div>

    </div>

    <div class="col md-6">

            <div class="card">

                <div class="card-header">
                    Текущие интерфейсы
                </div>

                <div class="card-body">
                    {% for current in current_overlays %}
                    {{ current | safe }} <br>
                    {%  endfor %}
                </div>

            </div>
    </div>
</div>



{% endblock %}

{% block scripts %}

<script src="/static/js/select_options_button_handler.js"></script>
<script>
let clear_buttons = document.querySelectorAll('.clear-btn');

clear_buttons.forEach((clear_button) => {
    clear_button.addEventListener('click', () => {
        let parentDiv = clear_button.closest(".interface-group");
        let radioButtons = parentDiv.querySelectorAll('input[type="radio"]');
        radioButtons.forEach((radioButton) => {
        radioButton.checked = false;
        })
    })
})
</script>
{% endblock %}